name: lint

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - tests/**

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.8.0
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.8.0
          args: format --check
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@v3
        name: Install PDM
      - run: pdm install
      - run: pdm run mypy --install-types --non-interactive
